//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transportes_3_Capas_Gen_9.WS_Calculadora {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_Calculadora.WS_CalculadoraSoap")]
    public interface WS_CalculadoraSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Transportes_3_Capas_Gen_9.WS_Calculadora.HelloWorldResponse HelloWorld(Transportes_3_Capas_Gen_9.WS_Calculadora.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Transportes_3_Capas_Gen_9.WS_Calculadora.HelloWorldResponse> HelloWorldAsync(Transportes_3_Capas_Gen_9.WS_Calculadora.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Suma", ReplyAction="*")]
        float Suma(float a, float b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Suma", ReplyAction="*")]
        System.Threading.Tasks.Task<float> SumaAsync(float a, float b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Resta", ReplyAction="*")]
        float Resta(float a, float b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Resta", ReplyAction="*")]
        System.Threading.Tasks.Task<float> RestaAsync(float a, float b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplicacion", ReplyAction="*")]
        float Multiplicacion(float a, float b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplicacion", ReplyAction="*")]
        System.Threading.Tasks.Task<float> MultiplicacionAsync(float a, float b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Division", ReplyAction="*")]
        float Division(float a, float b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Division", ReplyAction="*")]
        System.Threading.Tasks.Task<float> DivisionAsync(float a, float b);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Transportes_3_Capas_Gen_9.WS_Calculadora.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Transportes_3_Capas_Gen_9.WS_Calculadora.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Transportes_3_Capas_Gen_9.WS_Calculadora.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Transportes_3_Capas_Gen_9.WS_Calculadora.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_CalculadoraSoapChannel : Transportes_3_Capas_Gen_9.WS_Calculadora.WS_CalculadoraSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_CalculadoraSoapClient : System.ServiceModel.ClientBase<Transportes_3_Capas_Gen_9.WS_Calculadora.WS_CalculadoraSoap>, Transportes_3_Capas_Gen_9.WS_Calculadora.WS_CalculadoraSoap {
        
        public WS_CalculadoraSoapClient() {
        }
        
        public WS_CalculadoraSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_CalculadoraSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_CalculadoraSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_CalculadoraSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Transportes_3_Capas_Gen_9.WS_Calculadora.HelloWorldResponse Transportes_3_Capas_Gen_9.WS_Calculadora.WS_CalculadoraSoap.HelloWorld(Transportes_3_Capas_Gen_9.WS_Calculadora.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Transportes_3_Capas_Gen_9.WS_Calculadora.HelloWorldRequest inValue = new Transportes_3_Capas_Gen_9.WS_Calculadora.HelloWorldRequest();
            inValue.Body = new Transportes_3_Capas_Gen_9.WS_Calculadora.HelloWorldRequestBody();
            Transportes_3_Capas_Gen_9.WS_Calculadora.HelloWorldResponse retVal = ((Transportes_3_Capas_Gen_9.WS_Calculadora.WS_CalculadoraSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Transportes_3_Capas_Gen_9.WS_Calculadora.HelloWorldResponse> Transportes_3_Capas_Gen_9.WS_Calculadora.WS_CalculadoraSoap.HelloWorldAsync(Transportes_3_Capas_Gen_9.WS_Calculadora.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Transportes_3_Capas_Gen_9.WS_Calculadora.HelloWorldResponse> HelloWorldAsync() {
            Transportes_3_Capas_Gen_9.WS_Calculadora.HelloWorldRequest inValue = new Transportes_3_Capas_Gen_9.WS_Calculadora.HelloWorldRequest();
            inValue.Body = new Transportes_3_Capas_Gen_9.WS_Calculadora.HelloWorldRequestBody();
            return ((Transportes_3_Capas_Gen_9.WS_Calculadora.WS_CalculadoraSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public float Suma(float a, float b) {
            return base.Channel.Suma(a, b);
        }
        
        public System.Threading.Tasks.Task<float> SumaAsync(float a, float b) {
            return base.Channel.SumaAsync(a, b);
        }
        
        public float Resta(float a, float b) {
            return base.Channel.Resta(a, b);
        }
        
        public System.Threading.Tasks.Task<float> RestaAsync(float a, float b) {
            return base.Channel.RestaAsync(a, b);
        }
        
        public float Multiplicacion(float a, float b) {
            return base.Channel.Multiplicacion(a, b);
        }
        
        public System.Threading.Tasks.Task<float> MultiplicacionAsync(float a, float b) {
            return base.Channel.MultiplicacionAsync(a, b);
        }
        
        public float Division(float a, float b) {
            return base.Channel.Division(a, b);
        }
        
        public System.Threading.Tasks.Task<float> DivisionAsync(float a, float b) {
            return base.Channel.DivisionAsync(a, b);
        }
    }
}
